WebApplication1/Models/Birth.cs
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;
namespace WebApplication1.Models;

public class Birth
{
    public string? imie {  get; set; }

    public DateTime? data_ur { get; set; }

    public string ErrorrMessage;

    public bool IsValid()
    {
        if(imie is null)
        {
            ErrorrMessage = "Brakuje parametru imie.";
            return false;
        }

        if (data_ur is null)
        {
            ErrorrMessage = "Brakuje parametru data urodzenia.";
            return false;
        }

        if(data_ur > DateTime.Now)
        {
            ErrorrMessage = "Data urodzin musi być wcześniejsza od daty bieżącej.";
            return false;
        }


        return true;
    }


    public int Birth_fun()
    {
        return DateTime.Now.Year  - data_ur.Value.Year;
    }
}

WebApplication1/Models/Calculator.cs
namespace WebApplication1.Models;

public enum Operators
{
    Unknown, Add, Mul, Sub, Div
        
}

public class Calculator
{
    public Operators? op { get; set; }
    
    public double? a { get; set; } 
    
    public double? b { get; set; }

    public String Op
    {
        get
        {
            switch (op)
            {
                case Operators.Add:
                    return "+";
                case Operators.Sub:
                    return "-";
                case Operators.Mul:
                    return "*";
                case Operators.Div:
                   return "/";
                default:
                    return "";
            
            }
        }
    }

    public object ErrorMessage { get; set; }

    public bool IsValid()
    {
        if(a is null || b is null || op is null) return false;
        return true;
    }

    public double Calculate()
    {
        switch (op)
        {
            case Operators.Add:                
                return (double) (a + b);            
            case Operators.Sub:                
                return (double) (a - b);            
            case Operators.Mul:                
                return (double) (a * b);            
            case Operators.Div:                
                return (double) (a / b);            
            default: 
                return double.NaN;
        }
    }
}
    

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApplication1/Controllers/BirthController.cs
using WebApplication1.Models;
using Microsoft.AspNetCore.Mvc;


namespace WebApplication1.Controllers;

public class BirthController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Result([FromForm]Birth model)
    {
        if(!model.IsValid())
        {
            return View("Error", model);
        }

        return View(model);
    }

    public IActionResult Form() 
    {
        return View();
    }
}

WebApplication1/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers;

public class CalculatorController : Controller
{
    public enum Operator
    {
        Unknown, Add, Mul, Sub, Div
        
    }

    public IActionResult Form()
    {
        return View();  
    }

    [HttpPost]
    
    public IActionResult Result([FromForm] Calculator model)
    {
        if (!model.IsValid())
        {
            return View("Error",model);
        }
        return View(model);
    }
}

WebApplication1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Calculator(string op, double? a, double? b)
    {
        if (a is null || b is null)
        {
            ViewBag.ErrorMessage = "Niepoprawny format liczby w parametrze a lub b";
            return View("CustomError");
        }
        //dodaj obsługę błędu dla op, jeśli jest inny od add, syb, mul, div
        if (op != "add" && op != "sub" && op != "mul" && op != "div")
        {
            ViewBag.ErrorMessage = "Błąd parametru";
            return View("CustomError");
        }
        
        ViewBag.op = op;
        ViewBag.a = a;
        ViewBag.b = b;
        switch (op)
        {
            case "add":
                ViewBag.result = a + b;
                ViewBag.op = "+";
                break;
            case "sub":
                ViewBag.result = a - b;
                ViewBag.op = "-";
                break;
            case "mul":
                ViewBag.result = a * b;
                ViewBag.op = "*";
                break;
            case "div":
                ViewBag.result = a / b;
                ViewBag.op = ":";
                break;
            
        }
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebApplication1/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Birth calculator</h2>
<form action="Result" method="post">
    <div class="mb-3">
        <label class="form-label" for="x">Twoje imie: </label>
        <input class="form-control" type="text" name="imie" step="0.00001" id="x" />
    </div>               
    <div class="mb-3">
        <label class="form-label" for="y">Data urodzenia:</label>
        <input class="form-control" type="date" name="data_ur" step="0.00001" id="y" />
    </div>
    <div class="mb-3">
        <button class="btn btn-primary" type="submit">Oblicz</button>
    </div>
</form>

WebApplication1/Views/Birth/Result.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Birth calculator:</h2>
<div></div>
<h2>Witaj @Model.imie ! Masz @Model.Birth_fun() lat/(a).</h2>

WebApplication1/Views/Calculator/Form.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="">
<head>
    <title>title</title>
</head>
<body>
<div>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6">
                <h2>Kalkulator</h2>
                <form action="Result" method="Post">
                    <div class="mb-3">
                        <label class="form-label" for="x">Liczba 1</label>
                        <input class="form-control" type="number" name="a" step="0.00001" id="x"/>
                    </div>
                    <select name="op">
                        <option value="Add">+</option>
                        <option value="Sub">&minus;</option>
                        <option value="Mul">&times;</option>
                        <option value="Div">&divide;</option>
                    </select>
                    <div class="mb-3">
                        <label class="form-label" for="y">Liczba 2</label>
                        <input class="form-control" type="number" name="b" step="0.00001" id="y"/>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Oblicz</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

WebApplication1/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>@Model.a<b>@Model.Op</b>@Model.b = @Model.Calculate()</h3>

WebApplication1/Views/Home/About.cshtml
@model dynamic



<!DOCTYPE html>

<html>
<head>
    <title>About</title>
</head>
<body>
<div>
    <h2>Application created by Julia Przebinda</h2>
</div>
</body>
</html>

WebApplication1/Views/Home/Calculator.cshtml
@{
    ViewBag.Title = "Kalkulator";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<p>Wynik obliczeń: @ViewBag.a @ViewBag.op @ViewBag.b = @ViewBag.result</p>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Views/Shared/CustomError.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Błąd kalkulatora: @ViewBag.ErrorMessage</h2>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Birth</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>